#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
PROJECT_ROOT="$SCRIPT_DIR"
ENV_FILE="${CODEX_FEISHU_ENV:-$HOME/.config/codex-feishu/env}"
BOOTSTRAP_LOG="${TMPDIR:-/tmp}/codex-feishu-bootstrap.log"
TEMP_PID=""
export PATH="$HOME/.pixi/bin:$HOME/.local/bin:$PATH"

cleanup() {
  if [[ -n "$TEMP_PID" ]] && kill -0 "$TEMP_PID" 2>/dev/null; then
    kill "$TEMP_PID" 2>/dev/null || true
    wait "$TEMP_PID" 2>/dev/null || true
  fi
}
trap cleanup EXIT INT TERM

require_value() {
  local name="$1" value="$2"
  [[ -n "$value" ]] || { warn "$name 不能为空。"; exit 1; }
  [[ "$value" != *$'\n'* && "$value" != *$'\r'* ]] || {
    warn "$name 不能包含换行。"
    exit 1
  }
}

require_shell_safe_value() {
  local name="$1" value="$2"
  [[ "$value" =~ ^[A-Za-z0-9_./:@+-]+$ ]] || {
    warn "$name 含有空格或 shell 特殊字符，当前配置文件无法安全保存该值。"
    exit 1
  }
}

mkdir -p "$(dirname "$ENV_FILE")"
umask 077

banner "飞书 Codex Bridge · macOS 配置"

command -v pixi >/dev/null 2>&1 || {
  warn "未找到 pixi。请先安装 Pixi，再重新运行本向导：https://pixi.sh"
  exit 1
}
if [[ ! -x "$HOME/.local/bin/codex" ]] && ! command -v codex >/dev/null 2>&1; then
  warn "未找到 Codex CLI。请先安装并登录 Codex，再重新运行本向导。"
  exit 1
fi

say "正在按 pixi.lock 安装项目依赖……"
(
  cd "$PROJECT_ROOT"
  pixi install --locked
)

stage "创建并发布飞书应用"
say "浏览器将打开飞书开放平台。创建一个企业自建应用，并启用机器人能力。"
open_url "https://open.feishu.cn/app"
step "权限管理：添加 im:message.p2p_msg:readonly"
step "权限管理：添加 im:message.group_at_msg:readonly"
step "权限管理：添加 im:message.group_msg.include_bot:read"
step "权限管理：添加 im:message:send_as_bot"
step "权限管理：添加 im:chat:create"
step "事件与回调：选择“使用长连接接收事件”，添加 im.message.receive_v1。"
step "可用范围第一次只加入你自己；随后在“版本管理与发布”中创建版本并发布。"
step "最后进入“凭证与基础信息”，准备好 App ID 和 App Secret。"
pause "完成并发布后按 Enter 继续。"

stage "保存应用凭据"
say "凭据只写入本机 ${ENV_FILE}；App Secret 输入时不会显示。"
ask FEISHU_APP_ID "粘贴 App ID（通常以 cli_ 开头）："
ask_secret FEISHU_APP_SECRET "粘贴 App Secret："
require_value "FEISHU_APP_ID" "$FEISHU_APP_ID"
require_value "FEISHU_APP_SECRET" "$FEISHU_APP_SECRET"
require_shell_safe_value "FEISHU_APP_ID" "$FEISHU_APP_ID"
require_shell_safe_value "FEISHU_APP_SECRET" "$FEISHU_APP_SECRET"

ask CODEX_INITIAL_CWD "Codex 默认目录（直接回车使用 /Users/bytedance/Projects）："
CODEX_INITIAL_CWD="${CODEX_INITIAL_CWD:-/Users/bytedance/Projects}"
[[ -d "$CODEX_INITIAL_CWD" ]] || { warn "目录不存在：$CODEX_INITIAL_CWD"; exit 1; }
require_shell_safe_value "CODEX_INITIAL_CWD" "$CODEX_INITIAL_CWD"

FEISHU_ALLOWED_OPEN_ID=$(_existing FEISHU_ALLOWED_OPEN_ID || true)
CODEX_MODEL=$(_existing CODEX_MODEL || true)
CODEX_MODEL="${CODEX_MODEL:-gpt-5.6-sol}"
CODEX_REASONING_EFFORT=$(_existing CODEX_REASONING_EFFORT || true)
CODEX_REASONING_EFFORT="${CODEX_REASONING_EFFORT:-high}"
CODEX_SERVICE_TIER=$(_existing CODEX_SERVICE_TIER || true)
CODEX_SERVICE_TIER="${CODEX_SERVICE_TIER:-fast}"
write_env FEISHU_APP_ID "$FEISHU_APP_ID"
write_env FEISHU_APP_SECRET "$FEISHU_APP_SECRET"
write_env FEISHU_ALLOWED_OPEN_ID "$FEISHU_ALLOWED_OPEN_ID"
write_env CODEX_INITIAL_CWD "$CODEX_INITIAL_CWD"
write_env CODEX_MODEL "$CODEX_MODEL"
write_env CODEX_REASONING_EFFORT "$CODEX_REASONING_EFFORT"
write_env CODEX_SERVICE_TIER "$CODEX_SERVICE_TIER"
chmod 600 "$ENV_FILE"

stage "获取并写入 Open ID"
if [[ -n "$FEISHU_ALLOWED_OPEN_ID" ]]; then
  say "配置文件里已有 Open ID；直接回车可保留。"
  ask FEISHU_ALLOWED_OPEN_ID "Open ID："
else
  say "现在会临时启动 Bridge。它只用于识别你的飞书 Open ID。"
  : > "$BOOTSTRAP_LOG"
  set -a
  # shellcheck disable=SC1090
  source "$ENV_FILE"
  set +a
  (
    cd "$PROJECT_ROOT"
    exec "$PROJECT_ROOT/.pixi/envs/default/bin/python" -u bridge.py
  ) >>"$BOOTSTRAP_LOG" 2>&1 &
  TEMP_PID=$!
  sleep 3
  if ! kill -0 "$TEMP_PID" 2>/dev/null; then
    warn "临时 Bridge 启动失败，最近日志如下："
    tail -20 "$BOOTSTRAP_LOG" || true
    exit 1
  fi
  step "打开飞书，私聊刚创建的机器人并发送“你好”。"
  step "机器人会回复“你的飞书 Open ID 是：ou_...”，复制完整的 ou_...。"
  ask FEISHU_ALLOWED_OPEN_ID "粘贴你的 Open ID："
  kill "$TEMP_PID" 2>/dev/null || true
  wait "$TEMP_PID" 2>/dev/null || true
  TEMP_PID=""
fi
require_value "FEISHU_ALLOWED_OPEN_ID" "$FEISHU_ALLOWED_OPEN_ID"
require_shell_safe_value "FEISHU_ALLOWED_OPEN_ID" "$FEISHU_ALLOWED_OPEN_ID"
[[ "$FEISHU_ALLOWED_OPEN_ID" == ou_* ]] || { warn "Open ID 应以 ou_ 开头。"; exit 1; }
write_env FEISHU_ALLOWED_OPEN_ID "$FEISHU_ALLOWED_OPEN_ID"
chmod 600 "$ENV_FILE"

stage "启动并验收 Bridge"
say "将使用本机现有的 ChatGPT/Codex 登录状态启动后台 Bridge。"
(
  cd "$PROJECT_ROOT"
  pixi run stop
  pixi run start
  pixi run status
)
step "回到飞书私聊机器人，发送 /status 和 /pwd。"
step "再发送：请只回复“连接成功”，不要运行命令，不要修改任何文件。"
if ! confirm "飞书是否已正常回复？"; then
  warn "请查看 $HOME/.local/state/codex-feishu.log，并重新运行本向导。"
  exit 1
fi

finish
